config/routes.rb
Reconectese::Application.routes.draw do

  scope "(:locale)", locale: /en|es/ do

    get "static_pages/help"

    resources :visitors, only: [:new, :create]
    resources :contacts, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, :articles, :sections

    resources :articles do
      resources :article_contents, shallow: true
    end

    root "static_pages#home"

    match '/signup', to: 'users#new', via: 'get'
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/compose', to: 'articles#new', via: 'get'
    match '/tagged', to: 'articles#tagged', via: 'get'
    match '/search_section', to: 'sections#search_section', via: 'get'
    #match '/article_sections', to: 'articles#sections', via: 'get'

  end

end

app/models/articles/article.rb
# == Schema Information
#
# Table name: articles
#
#  id               :integer          not null, primary key
#  title            :string(255)
#  description      :string(255)
#  status           :integer
#  author_id        :integer
#  date_published   :date
#  comments_enabled :boolean
#  featured         :boolean
#  views            :integer
#  created_at       :datetime
#  updated_at       :datetime
#

class Article < ActiveRecord::Base
  belongs_to :user, class_name: 'User', foreign_key: 'author_id', validate: true
  has_many :article_contents, :class_name => 'ArticleContent'
  has_many :article_photographs, :class_name => 'ArticlePhotos'
  has_many :sections, :class_name => 'Section', through: :article_contents
  acts_as_taggable

  default_scope {order('created_at DESC')}

  validates :title, presence: true, length: {maximum: 60}, uniqueness: {case_sensitive: false, :message => I18n.t(:article_title_exist)}
  validates :description, presence: true, length: {maximum: 3000}
  validates :status, presence: true, numericality: {only_integer: true}, inclusion: 0..1
  validates :author_id, presence: true

end

app/models/articles/article_content.rb
# == Schema Information
#
# Table name: article_contents
#
#  id            :integer          not null, primary key
#  article_id    :integer
#  section_id    :integer
#  description   :string(255)
#  status        :integer
#  display_order :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class ArticleContent < ActiveRecord::Base
  belongs_to :article, class_name: 'Article'
  belongs_to :section, class_name: 'Section'
  attr_accessor :new_section_name

  validates :article, presence: true
  validates :section, presence: true

  validates :description, presence: true, length: {maximum: 3000}
  validates :status, presence: true, numericality: {only_integer: true}, inclusion: 0..1
  validates :display_order, presence: true, numericality: {only_integer: true}


end

app/models/articles/article_contents.rb
# == Schema Information
#
# Table name: article_contents
#
#  id            :integer          not null, primary key
#  article_id    :integer
#  section_id    :integer
#  description   :string(255)
#  status        :integer
#  display_order :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class ArticleContents < ActiveRecord::Base
  belongs_to :article, class_name: 'Article'
  belongs_to :section, class_name: 'Section'

  validates :article, presence: true
  validates :section, presence: true

  validates :description, presence: true, length: {maximum: 3000}
  validates :status, presence: true, numericality: {only_integer: true}, inclusion: 0..1
  validates :display_order, presence: true, numericality: {only_integer: true}


end

app/models/articles/article_photos.rb
# == Schema Information
#
# Table name: article_photos
#
#  id            :integer          not null, primary key
#  article_id    :integer
#  section_id    :integer
#  photo_path    :string(255)
#  album_url     :string(255)
#  photo_content :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class ArticlePhotos < ActiveRecord::Base
  belongs_to :article, class_name: 'Article'
  belongs_to :section, class_name: 'Section'
  mount_uploader :photo_path, ImageUploader

  validates :article, presence: true
  validates :section, presence: true

  # validates :photo_content, presence: true, allow_nil: false
  #validates :photo_path, presence: true, allow_nil: false
  # validates :album_url, presence: true, allow_nil: false

  validate :has_one_photo_type

  private

  def has_one_photo_type
    if (photo_content == '' && album_url == '')
      errors.add(:base, "Should have one photo type")
    end
  end
end

app/models/articles/section.rb
# == Schema Information
#
# Table name: sections
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  status      :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Section < ActiveRecord::Base
  has_many :article_contents, :class_name => 'ArticleContent'
  has_many :articles, through: :article_contents

  has_many :article_photographs, :class_name => 'ArticlePhotos'
  has_many :articles, through: :article_photographs

  scope :active, -> { where(status: 0) }

  validates :name, presence: true, length: {maximum: 30}, uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {maximum: 60}
  validates :status, presence: true, numericality: {only_integer: true}, inclusion: 0..1

  def self.search(query)
    where("upper(name) like upper(?)", "%#{query}%")
  end

  def as_json(options)
    { id: id, text: name }
  end

end

app/controllers/articles_controller.rb
class ArticlesController< ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :create, :destroy]
  before_action :admin_user, only: :destroy

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(request_params)
      flash[:success] = t(:article_update_success)
      #redirect_to  edit_article_content_path(@article)
      #redirect_to article_article_contents_url(@article)
      render "article_contents/index"
    else
      render 'edit'
    end
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
  end

  def tagged
    if params[:tag].present?
      @articles = Article.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 10).order('title')
    else
      @articles = Article.all
    end
  end

  def index
    if params[:search]
      @articles = Article.where("title like (?)", "%#{params[:search]}%").paginate(page: params[:page], per_page: 10).order('title')
    else
      if params[:user_id]
        @user = User.find(params[:user_id])
        @articles = @user.articles.paginate(page: params[:page], per_page: 10).order('title')
      else
        @articles = Article.paginate(page: params[:page], per_page: 10).order('title')
      end
    end

  end

  def create
    if params[:article].present?
      @article = Article.new(title: params[:article][:title],
                             description: params[:article][:description],
                             status: params[:article][:status],
                             author_id: current_user.id)
      if @article.save
        flash[:success] = t(:article_create_success)
        #redirect_to articles_path(:user_id => current_user.id)
        # redireccionamos a la pagina de secciones... pero primero las pruebas!!
        #Ok! redirect_to new_article_content_path(:article_id => @article.id)

        redirect_to new_article_article_content_path(@article)
      else
        flash[:error] = t(:article_create_error)
        render :new
      end
    end
  end

  def destroy

  end

  private
  def request_params
    params.require(:article).permit(:title, :description, :status)
  end

  # def signed_in_user
  #   unless signed_in?
  #     store_location
  #     redirect_to signin_url, notice: t(:sign_in_notice)
  #   end
  # end


end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/articles/_article.html.erb
<li>
  <p>
  <h4><%= link_to article.title, article, data: {no_turbolink: true} %>
    <% if signed_in? && is_admin? %>
        <%= create_delete_icon(article, 'right') %>
        <%= create_edit_icon(edit_article_path(article), 'right') %>
    <% end %>
  </h4>


  </p>
  <p><%= article.description %>
  </p>
    <span class="timestamp">
    <%= t(:posted_ago_1) + ' ' + time_ago_in_words(article.created_at) + ' ' +t(:posted_ago_2) %>
  </span>
</li>

app/views/articles/_article_contents.html.erb
<section>
  <p class="title" data-section-title><a href="#"><%= article_content.section.description %></a>
  </p>
  <div class="content" data-section-content>
    <p> <%= article_content.description %></p>
  </div>
</section>

app/views/articles/_article_photographs.html.erb
<li>
  <%= image_tag article_photographs.photo_path.url %>
  <div class="orbit-caption">
    <strong><%= article_photographs.section.description %></strong><br>
    <%= article_photographs.photo_content %>
  </div>
</li>

app/views/articles/_tags.html.erb
<section>
  <h4>Tags</h4>
  <ul class="list-unstyled inline-list blog-tags">
    <% tags.each do |t| %>
        <li><%= link_to "<i class='icon-tags'></i>#{t.name}".html_safe, tagged_url(:tag => t.name) %> </li>
    <% end %>
  </ul>
</section>

app/views/articles/contents.html.erb
<% content_for :title do
  t(:articles) %>
<% end %>
<% content_for :description do
  t(:articles) %>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: t(:articles) %>
<%= link_to t(:list_my_articles), articles_path(:user_id => current_user) %>

<!-- Start: Blogs List -->
<div class="row">
  <!-- blog entry -->
  <section class="small-12 large-8 column">
    <article class="blog-item">
      <h2><%= link_to @article.title, @article %></h2>

      <p><%= @article.description %></p>

      <div class="blog-img-thumb">
        <%#= image_tag "work/img_2.jpg" %>
      </div>

      <div class="row">
        <section class="small-12 large-12 column">
          <div id="faq-block">

            <% @article.article_contents.each do |ac| %>
                <div class="docs section-container accordion" data-section="accordion" data-options="one_up: false">
                  <%= render 'article_contents', article_content: ac %>
                </div>
            <% end %>

          </div>
        </section>
      </div>

      <blockquote>
        <p>WWWWWWWWWWWWWWWWWWWWWWWWWWWW</p>
        <small>Someone famous <cite title="Source Title">Source Title</cite></small>
      </blockquote>


    </article>
    <div class="blog-comments">
      <h3>Comments</h3>
      <ol class="blog-comments">
        <li class="comment">
          <div class="comment-list">
            <div class="comment-author">
              <%= image_tag "team_1.jpg", class: "author-img" %>
              <div class="author-deets">
                <h3 class="author">Wanda Wilson</h3>
                <span class="comment-date"><a href="#">Aug 17th, 2013</a></span></div>
            </div>
            <div class="comment-text">
              <p>ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut
                felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros
                eu erat. Aliquam erat volutpat. Nam dui mi</p>
              <a href="#" class="reply"><i class="icon-reply"></i> Reply</a>
            </div>
          </div>
          <ul>
            <li class="comment">
              <div class="comment-list">
                <div class="comment-author">
                  <img alt="#" src="img/team_2.jpg" class="author-img">

                  <div class="author-deets">
                    <h3 class="author">Wanda Wilson</h3>
                    <span class="comment-date"><a href="#">Aug 17th, 2013</a></span></div>
                </div>
                <div class="comment-text">
                  <p>ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis.
                    Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna
                    eros eu erat. Aliquam erat volutpat. Nam dui mi</p>
                  <a href="#" class="reply"><i class="icon-reply"></i> Reply</a>
                </div>
              </div>
            </li>
          </ul>
        </li>
        <li class="comment">
          <div class="comment-list">
            <div class="comment-author">
              <img alt="#" src="img/team_3.jpg" class="author-img">

              <div class="author-deets">
                <h3 class="author">Wanda Wilson</h3>
                <span class="comment-date"><a href="#">Aug 17th, 2013</a></span></div>
            </div>
            <div class="comment-text">
              <p>ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut
                felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros
                eu erat. Aliquam erat volutpat. Nam dui mi</p>
              <a href="#" class="reply"><i class="icon-reply"></i> Reply</a>
            </div>
          </div>
        </li>
      </ol>
      <div class="comment-form">
        <h2>Leave a comment</h2>

        <form class="contactform">
          <div class="item item-pair">
            <label for="FullName">Full Name
              <input type="text" name="FullName" id="FullName" class="cat_textbox" maxlength="255">
            </label>
            <label for="EmailAddress">Email Address
              <input type="text" name="EmailAddress" id="EmailAddress" class="cat_textbox" maxlength="255">
            </label>
          </div>
          <div class="item">
            <label for="Website">Website
              <input type="text" name="Website" id="Website" class="cat_textbox" maxlength="255">
            </label>
          </div>
          <div class="item">
            <label>Comments</label>
            <textarea cols="10" rows="4" class="cat_listbox"></textarea>
          </div>
          <div class="item">
            <input class="small button secondary" type="submit" value="Submit" id="catwebformbutton">
          </div>
        </form>
      </div>
    </div>

  </section>
  <!-- end blog entry -->
  <!-- aside -->
  <aside class="small-12 large-4 column blog-aside">

    <section>
      <div class="row">
        <ul id="featured1" data-orbit data-options="timer_speed:5000;">

          <% @article.article_photographs.each do |ap| %>
              <%= render 'article_photographs', article_photographs: ap %>
          <% end %>

          <li>
            <%= image_tag "work/img_2.jpg" %>
            <div class="orbit-caption">
              Caption Two. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
            </div>
          </li>
          <li>
            <%= image_tag "work/img_3.jpg" %>
            <div class="orbit-caption">
              Caption Three. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis
              egestas.
            </div>
          </li>
        </ul>
      </div>
    </section>


    <hr>
    <div class="postdetails">

      <ul class="list-unstyled inline-list blog-info">
        <li><i class="icon-calendar"></i> May 22, 2013</li>
        <li><i class="icon-pencil"></i> Abc Anderson</li>
        <li><i class="icon-comments"></i> <a href="#">2 Comments</a></li>
      </ul>
    </div>
    <hr>

    <%= render 'tags', tags: @article.tags %>

    <hr>
    <section class="categori-list">
      <h4>Categories</h4>
      <ul class="list-unstyled nav-list">
        <li class="active"><a href="#">Letuer adipi scing</a></li>
        <li><a href="#">Amet adipi consect sci ng</a></li>
        <li><a href="#"> dolor adipi sci consect</a></li>
        <li><a href="#">Letuer consect adipi dolor</a></li>
        <li><a href="#">Letuer adipi consect sci ng</a></li>
        <li><a href="#">Letuer dolor adipi sci consect</a></li>
        <li><a href="#">Zetuer consect adipi dolor</a></li>
        <li><a href="#">Letuer adipi consect sci ng</a></li>
        <li><a href="#">Bmet dolor adipi sci consect</a></li>
        <li><a href="#">Amteret consect adipi dolor</a></li>
      </ul>
    </section>

  </aside>
  <!-- aside -->
</div>
<!-- End : Blogs List -->

app/views/articles/edit.html.erb
<% content_for :title do
  t(:article_edit_title) %>
<% end %>
<% content_for :description do
  t(:article_edit_title) %>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: t(:article_edit_title) %>

<!-- Start:  Login Form-->
<section class="row" id="articles">
  <div class="small-12 large-12 column">
    <h2 class="aligncenter title"><%= t(:article_edit_description) %></h2>

    <div class="form">
      <%= simple_form_for @article do |form| %>
          <fieldset>
            <%= render 'layouts/error_messages', object: form.object %>

            <div class="row">
              <div class="large-12 columns">
                <h3><%= t(:article_form_title) %></h3>
                <%= form.input :title, error: false, label: false %>
              </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <h3><%= t(:article_form_description) %></h3>
                <%= form.input :description, as: :text, error: false, label: false %>
                <%= form.hidden_field :status, value: '0' %>
              </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <%= form.button :submit, t(:article_edit_sections), class: 'submit right' %>
              </div>
            </div>
          </fieldset>
      <% end %>
    </div>

  </div>

</section>

app/views/articles/index.html.erb
<% content_for :title do
  t(:articles) %>
<% end %>
<% content_for :description do
  t(:articles) %>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: t(:articles) %>

<!-- Start:  Login Form-->
<section class="row">
  <div class="row">
    <div class="small-12 large-8  column">
      <h3><%= create_big_link('icon-leaf', t(:section_new_link), new_article_path) %></h3>
    </div>
  </div>

  <div class="row">
    <div class="small-12 large-4 column ">
      <%= will_paginate @articles, {previous_label: t(:previous_label), next_label: t(:next_label), renderer: FoundationPagination::Rails} %>
    </div>
    <div class="small-12 large-4 column ">
      <%= render 'layouts/search_bar', where_to_post: articles_path %>
    </div>
  </div>

  <div class="small-12 large-12 column ">
    <ul class="listado">
      <% @sections.each do |section| %>
          <%= render section %>
      <% end %>
    </ul>
  </div>
</section>
<p>Mariposa</p>

app/views/articles/new.html.erb
<% content_for :title do
  t(:article_new_title) %>
<% end %>
<% content_for :description do
  t(:article_new_title) %>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: t(:article_new_title) %>

<!-- Start:  Login Form-->
<section class="row" id="articles">
  <div class="small-12 large-12 column">
    <h2 class="aligncenter title"><%= t(:article_new_link) %></h2>

    <div class="form">
      <%= simple_form_for @article do |form| %>
          <fieldset>
            <%= render 'layouts/error_messages', object: form.object %>

            <div class="row">
              <div class="large-12 columns">
                <h3><%= t(:article_form_title) %></h3>
                <%= form.input :title, error: false, label: false %>
              </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <h3><%= t(:article_form_description) %></h3>
                <%= form.input :description, as: :text, error: false, label: false %>
                <%= form.hidden_field :status, value: '0' %>
              </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <%= form.button :submit, t(:create_button_label), class: 'submit right' %>
              </div>
            </div>
          </fieldset>
      <% end %>
    </div>

  </div>

</section>

app/views/articles/show.html.erb
<% content_for :title do
  t(:articles) %>
<% end %>
<% content_for :description do
  t(:articles) %>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: t(:articles) %>
<%= link_to t(:list_my_articles), articles_path(:user_id => current_user) %>

<!-- Start: Blogs List -->
<div class="row">
  <!-- blog entry -->
  <section class="small-12 large-8 column">
    <article class="blog-item">
      <h2><%= link_to @article.title, @article %></h2>

      <p><%= @article.description %></p>

      <div class="blog-img-thumb">
        <%#= image_tag "work/img_2.jpg" %>
      </div>

      <div class="row">
        <section class="small-12 large-12 column">
          <div id="faq-block">

            <% @article.article_contents.each do |ac| %>
                <div class="docs section-container accordion" data-section="accordion" data-options="one_up: false">
                  <%= render 'article_contents', article_content: ac %>
                </div>
            <% end %>

          </div>
        </section>
      </div>

      <blockquote>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit posuere erat a ante.</p>
        <small>Someone famous <cite title="Source Title">Source Title</cite></small>
      </blockquote>


    </article>
    <div class="blog-comments">
      <h3>Comments</h3>
      <ol class="blog-comments">
        <li class="comment">
          <div class="comment-list">
            <div class="comment-author">
              <%= image_tag "team_1.jpg", class: "author-img" %>
              <div class="author-deets">
                <h3 class="author">Wanda Wilson</h3>
                <span class="comment-date"><a href="#">Aug 17th, 2013</a></span></div>
            </div>
            <div class="comment-text">
              <p>ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut
                felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros
                eu erat. Aliquam erat volutpat. Nam dui mi</p>
              <a href="#" class="reply"><i class="icon-reply"></i> Reply</a>
            </div>
          </div>
          <ul>
            <li class="comment">
              <div class="comment-list">
                <div class="comment-author">
                  <img alt="#" src="img/team_2.jpg" class="author-img">

                  <div class="author-deets">
                    <h3 class="author">Wanda Wilson</h3>
                    <span class="comment-date"><a href="#">Aug 17th, 2013</a></span></div>
                </div>
                <div class="comment-text">
                  <p>ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis.
                    Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna
                    eros eu erat. Aliquam erat volutpat. Nam dui mi</p>
                  <a href="#" class="reply"><i class="icon-reply"></i> Reply</a>
                </div>
              </div>
            </li>
          </ul>
        </li>
        <li class="comment">
          <div class="comment-list">
            <div class="comment-author">
              <img alt="#" src="img/team_3.jpg" class="author-img">

              <div class="author-deets">
                <h3 class="author">Wanda Wilson</h3>
                <span class="comment-date"><a href="#">Aug 17th, 2013</a></span></div>
            </div>
            <div class="comment-text">
              <p>ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut
                felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros
                eu erat. Aliquam erat volutpat. Nam dui mi</p>
              <a href="#" class="reply"><i class="icon-reply"></i> Reply</a>
            </div>
          </div>
        </li>
      </ol>
      <div class="comment-form">
        <h2>Leave a comment</h2>

        <form class="contactform">
          <div class="item item-pair">
            <label for="FullName">Full Name
              <input type="text" name="FullName" id="FullName" class="cat_textbox" maxlength="255">
            </label>
            <label for="EmailAddress">Email Address
              <input type="text" name="EmailAddress" id="EmailAddress" class="cat_textbox" maxlength="255">
            </label>
          </div>
          <div class="item">
            <label for="Website">Website
              <input type="text" name="Website" id="Website" class="cat_textbox" maxlength="255">
            </label>
          </div>
          <div class="item">
            <label>Comments</label>
            <textarea cols="10" rows="4" class="cat_listbox"></textarea>
          </div>
          <div class="item">
            <input class="small button secondary" type="submit" value="Submit" id="catwebformbutton">
          </div>
        </form>
      </div>
    </div>

  </section>
  <!-- end blog entry -->
  <!-- aside -->
  <aside class="small-12 large-4 column blog-aside">

    <section>
      <div class="row">
        <ul id="featured1" data-orbit data-options="timer_speed:5000;">

          <% @article.article_photographs.each do |ap| %>
              <%= render 'article_photographs', article_photographs: ap %>
          <% end %>

          <li>
            <%= image_tag "work/img_2.jpg" %>
            <div class="orbit-caption">
              Caption Two. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
            </div>
          </li>
          <li>
            <%= image_tag "work/img_3.jpg" %>
            <div class="orbit-caption">
              Caption Three. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis
              egestas.
            </div>
          </li>
        </ul>
      </div>
    </section>


    <hr>
    <div class="postdetails">

      <ul class="list-unstyled inline-list blog-info">
        <li><i class="icon-calendar"></i> May 22, 2013</li>
        <li><i class="icon-pencil"></i> Abc Anderson</li>
        <li><i class="icon-comments"></i> <a href="#">2 Comments</a></li>
      </ul>
    </div>
    <hr>

    <%= render 'tags', tags: @article.tags %>

    <hr>
    <section class="categori-list">
      <h4>Categories</h4>
      <ul class="list-unstyled nav-list">
        <li class="active"><a href="#">Letuer adipi scing</a></li>
        <li><a href="#">Amet adipi consect sci ng</a></li>
        <li><a href="#"> dolor adipi sci consect</a></li>
        <li><a href="#">Letuer consect adipi dolor</a></li>
        <li><a href="#">Letuer adipi consect sci ng</a></li>
        <li><a href="#">Letuer dolor adipi sci consect</a></li>
        <li><a href="#">Zetuer consect adipi dolor</a></li>
        <li><a href="#">Letuer adipi consect sci ng</a></li>
        <li><a href="#">Bmet dolor adipi sci consect</a></li>
        <li><a href="#">Amteret consect adipi dolor</a></li>
      </ul>
    </section>

  </aside>
  <!-- aside -->
</div>
<!-- End : Blogs List -->

app/views/articles/tagged.html.erb
<% content_for :title do
  t(:articles) %>
<% end %>
<% content_for :description do
  t(:articles) %>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: "#{t(:articles)} #{t(:articles_tagged_with)} #{params[:tag]}" %>

<!-- Start:  Login Form-->
<article class="row">
  <div class="row">
    <div class="small-12 large-12  column">
      <h3><%= create_big_link('icon-leaf', t(:article_new_link), new_article_path) %></h3>
    </div>
  </div>
  <br>

  <div class="row">
    <div class="small-12 large-4 column ">
      <%= will_paginate @articles, {previous_label: t(:previous_label), next_label: t(:next_label), renderer: FoundationPagination::Rails} %>
    </div>
    <div class="small-12 large-4 column ">
      <%= render 'layouts/search_bar', where_to_post: tagged_path %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 large-12 column ">
      <ul class="listado">
        <% @articles.each do |article| %>
            <%= render article %>
        <% end %>
      </ul>
    </div>
  </div>
</article>
<p>Mariposa</p>