config/routes.rb
Reconectese::Application.routes.draw do

  scope "(:locale)", locale: /en|es/ do

    get "static_pages/help"

    resources :visitors, only: [:new, :create]
    resources :contacts, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, :articles, :sections

    resources :articles do
      resources :article_contents, shallow: true
    end

    root "static_pages#home"

    match '/signup', to: 'users#new', via: 'get'
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/compose', to: 'articles#new', via: 'get'
    match '/tagged', to: 'articles#tagged', via: 'get'
    match '/search_section', to: 'sections#search_section', via: 'get'
    #match '/article_sections', to: 'articles#sections', via: 'get'

  end

end

app/models/articles/section.rb
# == Schema Information
#
# Table name: sections
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  status      :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Section < ActiveRecord::Base
  has_many :article_contents, :class_name => 'ArticleContent'
  has_many :articles, through: :article_contents

  has_many :article_photographs, :class_name => 'ArticlePhotos'
  has_many :articles, through: :article_photographs

  scope :active, -> { where(status: 0) }

  validates :name, presence: true, length: {maximum: 30}, uniqueness: {case_sensitive: false}
  validates :description, presence: true, length: {maximum: 60}
  validates :status, presence: true, numericality: {only_integer: true}, inclusion: 0..1

  def self.search(query)
    where("upper(name) like upper(?)", "%#{query}%")
  end

  def as_json(options)
    { id: id, text: name }
  end

end

app/controllers/sections_controller.rb
class SectionsController< ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :admin_user, only: :destroy

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:success] = t(:section_update_success)
      redirect_to sections_path
    else
      render 'edit'
    end
  end

  def destroy
    Section.find(params[:id]).destroy
    flash[:success] = t(:section_destroy_success)
    redirect to sections_url
  end

  def new
    @section = Section.new
  end

  def show
    @section = Section.find(params[:id])
  end

  def index
    if params[:search]
      @sections = Section.active.search(params[:search]).paginate(page: params[:page], per_page: 10).order('name')
    else
      @sections = Section.active.paginate(page: params[:page], per_page: 10).order('name')
    end
    respond_to do |format|
      format.html
      format.json { render json: @sections }
    end
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:success] = t(:section_create_success)
      redirect_to sections_path
    else
      flash[:error] = t(:section_create_error)
      render :new
    end
  end

  def search_section
    @sections = Section.search(params[:q]).
        order('name') #.paginate(params[:page], per_page: 10)   # also add the total count to enable infinite scrolling

    sections_count = Section.search(params[:q]).count

    respond_to do |format|
      #format.json { render json: {total: sections_count, resources: @sections.map { |e| {id: e.id, text: "#{e.name} (#{e.description})"} }} }
      format.html
      format.json { render json: @sections }
    end
  end


  private
  def section_params
    params.require(:section).permit(:name, :description, :status, :q)
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: t(:sign_in_notice)
    end
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/views/sections/_section.html.erb
<li>
  <p>
  <h4><%= link_to section.name, section %>
    <% if current_user.admin? %>
        <%= create_delete_icon(section,'right') %>
    <% end %>
  </h4>
  </p>
  <p><%= section.description %>

  </p>
</li>

app/views/sections/index.html.erb
<% content_for :title do
  t(:sections) %>
<% end %>
<% content_for :description do
  t(:sections) %>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: t(:sections) %>

<!-- Start:  Login Form-->
<section class="row">
  <div class="row">
    <div class="small-12 large-8  column">
      <h3><%= create_big_link('icon-leaf', t(:section_new_link), new_section_path) %></h3>
    </div>
  </div>

  <div class="row">
    <div class="small-12 large-4 column ">
      <%= will_paginate @sections, {previous_label: t(:previous_label), next_label: t(:next_label), renderer: FoundationPagination::Rails} %>
    </div>
    <div class="small-12 large-4 column ">
      <%= render 'layouts/search_bar', where_to_post: sections_path %>
    </div>
  </div>

  <div class="small-12 large-12 column ">
    <ul class="listado">
      <% @sections.each do |section| %>
          <%= render section %>
      <% end %>
    </ul>
  </div>
</section>
<p>Gracias</p>

app/views/sections/show.html.erb
<% content_for :title do t(:section_edit_title)%>
<% end %>
<% content_for :description do t(:section_edit_title)%>
<% end %>
<%= render 'layouts/title', icono: "icon-leaf", titulo: t(:section_edit_title) %>

<!-- Start:  section form -->
<section class="row" id="sections">
  <div class="small-12 large-4 large-offset-2 column">
    <h3 class="aligncenter title"><%= t(:section_edit_header) %></h3>

    <div class="form">
      <%= simple_form_for @section do |form| %>
          <fieldset>
            <%= render 'layouts/error_messages', object: form.object %>
            <div class="clearfix">
              <div class="input">
                <%= form.input :name , error: false, label: t(:section_form_name) %>
              </div>
            </div>
            <div class="clearfix">
              <div class="input">
                <%= form.input :description , as: :text, error: false, label:t(:section_form_description)%>
                <%= form.hidden_field :status , value: '0' %>
              </div>
            </div>
            <div class="clearfix">
              <%= link_to sections_path do %>
                  <i class="icon-arrow-left dark-link"></i> <%= t(:cancel_button_label) %>
              <% end %>
            </div>
            <div class="clearfix">
              <%= link_to root_path do %>
                  <i class="icon-arrow-left dark-link"></i> <%= t(:cancel_button_label) %>
              <% end %>
            </div>
            <div class="actions">
              <%= form.button :submit, t(:save_button_label), class: 'submit' %>
            </div>
          </fieldset>
      <% end %>
    </div>

  </div>

</section>