config/routes.rb
Reconectese::Application.routes.draw do

  scope "(:locale)", locale: /en|es/ do

    get "static_pages/help"

    resources :visitors, only: [:new, :create]
    resources :contacts, only: [:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, :articles, :sections

    resources :articles do
      resources :article_contents, shallow: true
    end

    root "static_pages#home"

    match '/signup', to: 'users#new', via: 'get'
    match '/signin', to: 'sessions#new', via: 'get'
    match '/signout', to: 'sessions#destroy', via: 'delete'
    match '/compose', to: 'articles#new', via: 'get'
    match '/tagged', to: 'articles#tagged', via: 'get'
    match '/search_section', to: 'sections#search_section', via: 'get'
    #match '/article_sections', to: 'articles#sections', via: 'get'

  end

end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        Encontramos <%= pluralize(object.errors.count, "error", "errores") %> :
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div clas="row" id="footer">
  <div class="row widgets-block">
    <div class="small-12 large-3 column widget">
      <h4>Vida Sana</h4>

      <div class="flickr-widget">
        <script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?count=8&amp;display=latest&amp;size=s&amp;layout=x&amp;source=user&amp;user=15817260@N02"></script>
        <!-- "15817260@N02"  replace this with your flickr ID-->
        <div class="clear"></div>
      </div>
    </div>
    <div class="small-12 large-3 column widget">
      <h4>Navega</h4>
      <ul class="link-list">
        <li class="active"><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Nuestra mision', page_path('about') %></li>
        <li><%= link_to 'Contacto', new_contact_path %></li>

        <li><a href="#">Quienes somos</a></li>
        <li><a href="#">Nuestros servicios</a></li>
        <li><a href="#">Nuestro equipo</a></li>
        <li><a href="#">Busca productos</a></li>
        <li><a href="#">Mantente en contacto</a></li>
      </ul>
    </div>

    <div class="small-12 large-3 column widget">
      <h4>Mantente en contacto</h4>

      <p>
        <strong>La isla del encanto,Puerto Rico </strong><br/>
        PO Box 6630 <br/>
        Bayamon, PR 00960. <br/>
      </p>

      <p>
        <i class="icon-phone"></i> (123) 456-7890 <br>
        <i class="icon-envelope-alt"></i> enrique.tron@gmail.com
      </p>
    </div>

    <div class="small-12 large-3 column widget">
      <h4 class="title"> Suscribete</h4>

      <p>
        Por favor suscribase para recibir
        noticias y promociones de los
        articulos y productos que encontraras
        para mantener tu vida sana
      </p>

      <form class="form-inline">
        <input type="text" class="input-medium" placeholder="Your email">
        &nbsp;
        <button type="submit" class="small button secondary">Suscribete</button>
      </form>
    </div>
  </div>

  <div id="social-links" class="aligncenter">
    <a href="" class="up-arrow"><i class="icon-angle-up"></i></a>

    <div class="row">
      <a href="#"><i class="icon-facebook icon-circled icon-64"></i></a>
      <a href="#"><i class="icon-twitter icon-circled icon-64"></i></a>
      <a href="#"><i class="icon-google-plus icon-circled icon-64"></i></a>
      <a href="#"><i class="icon-linkedin icon-circled icon-64"></i></a>
      <a href="#"><i class="icon-pinterest icon-circled icon-64"></i></a>
      <a href="#"><i class="icon-tumblr-sign icon-circled icon-64"></i></a>
      <a href="#"><i class="icon-dribbble icon-circled icon-64"></i></a>
    </div>
    <div class="copyrights">
      &copy;2014 <a href="http://www.ad-says.com" target="_blank">Beetle Inc</a> All Rights Reserved.
    </div>
  </div>
</div>

app/views/layouts/_introb.html.erb
<li>
  <div class="row slider-box">
    <div class="slider-details small-12 large-7 columns">
      <h2 class="custom-animated fadeInUpBig">AAA</h2>
      <h4 class="custom-animated fadeInUpBig">AAA</h4>
      <p class="custom-animated fadeInUpBig"> AAA  magna. Donec sed odio dui. Praesent commodo cursus magna
        <br /><a href="" class="button small">Read More</a>
      </p>
    </div>
    <div class="slider-image small-12 large-5 columns custom-animated fadeInUpBig">
      <%= image_tag "slider/responsive.png", alt:"Build with foundation-4"  %>
    </div>
  </div>
</li>

app/views/layouts/_main_banner.html.erb
<!-- Start: Banner -->
<section id="banner">
  <div class="row">
    <div class="small-12 columns">
      <ul data-orbit data-options="timer_speed:8000; navigation_arrows: false;bullets:true;  pause_on_hover: false; resume_on_mouseout: true;">
        <%= render 'layouts/main_banner_detail',
                   heading: 'Build with foundation 4444',
                   sub_heading: 'Sub heading goes here',
                   content: 'Porta ac consectetur ac, estibulum at eros. Donec sed odio dui. vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna. Donec sed odio dui. Praesent commodo cursus magna',
                   reference: '#',
                   image: 'slider/foundation-4.png',
                   image_alt: "Build with foundation-4"
        %>
        <li>
          <div class="row slider-box">
            <div class="slider-details small-12 large-7 columns">
              <h2 class="custom-animated fadeInLeftBig">HTML 5</h2>
              <h4 class="custom-animated fadeInLeftBig">Sub heading goes here</h4>
              <p class="custom-animated fadeInLeftBig"> Porta ac consectetur estibulum at eros. Donec sed odio dui.estibulum at eros. Donec sed odio dui. ac, vestibulum at eros. Donec sed odio dui. Praesent commodo cursus magna. Donec sed odio dui. Praesent commodo cursus magna
                <br /><a href="" class="button small">Read More</a>
              </p>
            </div>
            <div class="slider-image small-12 large-5 columns custom-animated fadeInRightBig">
              <%= image_tag "slider/html5.png", alt:"Build with HTML5"  %>
            </div>
          </div>
        </li>
        <li>
          <div class="row slider-box">
            <div class="slider-details small-12 large-7 columns custom-animated rotateInDownLeft">
              <h2  >Build with CSS3</h2>
              <h4  >Sub heading goes here</h4>
              <p  > Porta ac consectetur ac, vestibulum at eros. Donec sed odio dui.  Donec sed odio dui Praesent estibulum at eros. Donec sed odio dui. commodo cursus magna. Donec sed odio dui. Praesent commodo cursus magna
                <br /><a href="" class="button small">Read More</a>
              </p>
            </div>
            <div class="slider-image small-12 large-5 columns custom-animated rotateInUpRight">
              <%= image_tag "slider/css3.png", alt:"Build with foundation-4"  %>
            </div>
          </div>
        </li>
        <li>
          <div class="row slider-box">
            <div class="slider-details small-12 large-7 columns">
              <h2 class="custom-animated fadeInUpBig">Fully Responsive </h2>
              <h4 class="custom-animated fadeInUpBig">Sub heading goes here</h4>
              <p class="custom-animated fadeInUpBig"> Porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Praesent commodo  sonec sed odio duicursus magna. Donec sed odio dui. Praesent commodo cursus magna
                <br /><a href="" class="button small">Read More</a>
              </p>
            </div>
            <div class="slider-image small-12 large-5 columns custom-animated fadeInUpBig">
              <%= image_tag "slider/responsive.png", alt:"Build with foundation-4"  %>
            </div>
          </div>
        </li>
        <%= render 'layouts/introb' %>
      </ul>
    </div>
  </div>
</section>
<!-- End: Banner -->

app/views/layouts/_main_banner_detail.html.erb
<li>
  <div class="row slider-box">
    <div class="slider-details small-12 large-7 columns">
      <h2 class="custom-animated fadeInUpBig"><%= heading %></h2>
      <h4 class="custom-animated fadeInUpBig"><%= sub_heading %></h4>
      <p class="custom-animated fadeInUpBig"> <%= content %>
        <br /><a href="<%= reference %>" class="button small">Lee mas</a>
      </p>
    </div>
    <div class="slider-image small-12 large-5 columns custom-animated fadeInRightBig">
      <!--img src="slider/foundation-4.png" alt="Build with foundation-4" /-->
      <%= image_tag image , alt:image_alt  %>

    </div>
  </div>
</li>

app/views/layouts/_main_features.html.erb
<!-- Start:  features-box -->
<div class="row" id="features" >
  <%= render 'layouts/main_features_detail', icono:'icon-desktop',
      header: 'Aprende a sembrar',
      content: 'Lorem ipsum dolor sit has ei ipsum  amet, has ei ipsum scaevola deseruisse am sea facilisis.',
      reference: '#'  %>

  <%= render 'layouts/main_features_detail', icono:'icon-mobile-phone',
      header: 'Comparte tus experiencias',
      content: 'Lorem ipsum dolor sit has ei ipsum  amet, has ei ipsum scaevola deseruisse am sea facilisis.',
      reference: '#'  %>

  <%= render 'layouts/main_features_detail', icono:'icon-html5 ',
      header: 'HTML5 & CSS 3',
      content: 'Lorem ipsum dolor sit has ei ipsum  amet, has ei ipsum scaevola deseruisse am sea facilisis.',
      reference: '#'  %>

  <%= render 'layouts/main_features_detail', icono:'icon-briefcase  ',
      header: 'Corporate Business',
      content: 'Lorem ipsum dolor sit has ei ipsum  amet, has ei ipsum scaevola deseruisse am sea facilisis.',
      reference: '#'  %>

</div>
<!-- End:  features-box -->

app/views/layouts/_main_features_detail.html.erb
<div class='small-12 large-3 columns aligncenter features-box'>
  <div class='features-img aligncenter'><i class="<%= icono %> icon-circled icon-64"></i></div>
  <div class='features-details'><h4><%= header %></h4>

    <p><%= content %></p><a href=<%= reference %>>Lee mas</a></div>
</div>

app/views/layouts/_main_recent.html.erb
<section id="recent-work">
  <div class="row">
    <h3 class="small-8 large-10 column">
      Entradas recientes
    </h3>

    <div class="small-4 large-2 column">
      <a href="#" class="button">Lee mas</a>
    </div>
  </div>
  <div class="row">
    <%= render 'layouts/main_recent_detail',
          image: 'work/img_1.jpg',
          alt:"Recent Work",
          header:'Portfolio Item #1',
          content:'Etiam porta sem malesuada magna mollis euismod.'
    %>

    <%= render 'layouts/main_recent_detail',
              image:"work/img_2.jpg",
              alt:"Recent Work",
              header:'Portfolio Item #2',
              content:'Etiam porta sem malesuada magna mollis euismod.'
    %>

    <%= render 'layouts/main_recent_detail',
              image:"work/img_3.jpg",
              alt:"Recent Work",
              header:'Portfolio Item #3',
              content:'Etiam porta sem malesuada magna mollis euismod.'
    %>

    <%= render 'layouts/main_recent_detail',
              image:"work/img_4.jpg",
              alt:"Recent Work",
              header:'Portfolio Item #4',
              content:'Etiam porta sem malesuada magna mollis euismod.'
    %>

  </div>
</section>

app/views/layouts/_main_recent_detail.html.erb
<div class="recent-box small-12 large-3 column">
  <a href="<%= image_path(image) %>" data-link="prettyPhoto[pp_gal]" class="thumbnail">
    <img src="<%= image_path(image) %>" alt="<%= alt %>">
  </a>
  <h4><%= header %></h4>
  <p><%= content %></p>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box radius <%= name.to_s %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 4 %>
<div class="row">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1>
          <a href="index.html" class="logo"><i class="icon-unlink"></i><span><%= t :web_title1 %></span><%= t :web_title2 %>
          </a></h1>
      </li>
      <li class="toggle-topbar"><a href="#"><i class="icon-reorder"></i></a></li>
    </ul>
    <section class="top-bar-section">
      <%= render 'layouts/navigation_links' %>
    </section>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="right">
  <li class="active"><%= link_to t(:home), root_path %></li>

  <li class="has-dropdown"><a href="#"><%= t(:articles) %></a>
    <ul class="dropdown">
      <li><%= link_to t(:new_article), compose_path %></li>
      <% if signed_in? %>
          <li><%= link_to t(:review_article), articles_path(:user_id => current_user) %></li>
      <% end %>
      <li><%= link_to t(:list_articles), articles_path %></li>
    </ul>
  </li>


  <% if signed_in? %>
      <li class="has-dropdown"><a href="#"><%= t(:my_account) %></a>
        <ul class="dropdown">
          <li><%= link_to t(:my_profile), user_path(current_user) %></li>
          <li><%= link_to t(:settings), edit_user_path(current_user) %></li>

          <li class="divider"></li>
          <li><%= link_to t(:sign_out), signout_path, method: "delete" %></li>
        </ul>
      </li>
  <% else %>
      <li><%= link_to t(:register), new_user_path %></li>
      <li><%= link_to t(:sign_in), signin_path %></li>
  <% end %>

  <li><%= link_to t(:contact), new_contact_path, data: {no_turbolink: true} %></li>

  <% if signed_in? && is_admin? %>
      <li class="has-dropdown"><a href="#"><%= t(:administration) %></a>
        <ul class="dropdown">
          <li><%= link_to t(:users), users_path %></li>
          <li><%= link_to t(:sections), sections_path %></li>
        </ul>
      </li>
  <% end %>


  <!--li class="has-dropdown"><a href="#">Portafolio</a>
    <ul class="dropdown">
      <li><a href="portfolio2.html">portafolio 2 col</a></li>
      <li><a href="portfolio3.html">portafolio 3 col</a></li>
      <li><a href="portfolio4.html">portafolio 4 col</a></li>
    </ul>
  </li-->

  <li class="has-dropdown"><a href="#">Extras </a>
    <ul class="dropdown">
      <li><a href="services.html">Servicios</a></li>
      <li><a href="blog.html">Blog</a></li>
      <li><%= link_to 'Nosotros', page_path('about') %></li>
      <li><a href="single-post.html">Single Post </a></li>
      <li><a href="project-details.html">Project Details </a></li>
      <li><a href="coming-soon.html">Coming Soon</a></li>
      <li><a href="gallery.html">Gallery </a></li>
      <li><a href="gallery-flickr.html">Gallery Flickr</a></li>
      <li><a href="gallery-video.html">Video Gallery</a></li>
      <li><a href="price-table.html">Price List</a></li>
      <li><a href="testimonials.html">Testimonials</a></li>
      <li><a href="quote.html">Request a Quote</a></li>
      <li><a href="faq.html">FAQ</a></li>
      <li><a href="icons.html">Buttons and Icons</a></li>
      <li><a href="404.html">404</a></li>
    </ul>
  </li>

</ul>

app/views/layouts/_search_bar.html.erb
<div class="">
  <%= form_tag where_to_post, :method => :get, id: "search-form" do %>
      <%= content_tag :div, class: "row collapse" do %>
          <%= content_tag :div, class: "small-8 columns" do %>
              <%= text_field_tag :search, params[:search], placeholder: t(:search_label), id: 'search_btn' %>
          <% end %>
          <%= content_tag :div, class: "small-2 columns" do %>
              <span class="postfix"><%= link_to raw("<i class=\"icon-search \"></i>"), '#', class: "block", :onclick => "$('#search-form').submit()".html_safe %></span>
          <% end %>
          <%= content_tag :div, class: "small-2 columns" do %>
            &nbsp;<%= link_to "Clear", '#', onclick: "$('#search_btn').val('');".html_safe, class: 'right inline' %>
          <% end %>
      <% end %>
  <% end %>
</div>

app/views/layouts/_title.html.erb
<div class="page-title">
  <div class="row">
    <div class="small-12 large-8 column">
      <h1  class="animated flipInX"><i class=<%= icono %>></i>
        <%= titulo %>
      </h1>
    </div>
    <div class="small-12 large-4 column">
      <ul class="breadcrumbs right">
        <li><a href="index.html">Home</a></li>
        <li class="current"><a href="#">About Us2</a></li>
      </ul>
    </div>
  </div>
</div>